### ISSUE TITLE
Carrier logo beside clock and at bottom when you open quick settings

### ISSUE THREAD

**Issue by Bobthahog** [zacharee/OneUITunerRedesign#1]
I have checked remove carrier logo and it worked for the lock screen but it still shows my carrier logo which is Sprint, up by my clock and at the bottom of the screen when I open my quick settings. I am on Sprint Samsung Galaxy note 10 plus running Android 10 with one UI 2.0.

**Comment by zacharee** [comment]
Version 12 has a new option for the logo at the bottom of the notification panel, and should hide the QS label as well when the status bar hide toggle is enabled.
