### ISSUE TITLE
Simply downloaded the oneuituner_SIGNED.apk and install twice, then s9+ bricked

### ISSUE THREAD

**Issue by cnyyk** [zacharee/OneUITunerRedesign#5]
Could you please tell me how to remove this app to let s9+ works normally?

1. download oneuituner_SIGNED.apk from https://github.com/zacharee/OneUITunerRedesign/blob/master/oneuituner_SIGNED.apk via download button.
2. install it. nothing changed.
3. install it again, s9+ restarted and loop restart.
4. bricked, enter error screen, shown as below:
![IMG_1427](https://user-images.githubusercontent.com/275233/73997630-0a034880-499a-11ea-801a-7592189f85d3.JPG)
![IMG_1428](https://user-images.githubusercontent.com/275233/73997642-11c2ed00-499a-11ea-896a-a30561479518.JPG)

**Comment by cnyyk** [comment]
Hold vol - when Samsung logo appears, can't boot into safe mode, still loop restart

**Comment by zacharee** [comment]
That isn't a valid APK to install. It shouldn't even be in the repo.

**Comment by cnyyk** [comment]
oh, no....
could you please tell me how to fix this / uninstall it from s9+?
can boot into recovery mode / fastboot mode.

**Comment by cnyyk** [comment]
could you please tell me the package name of oneuituner_SIGNED.apk?
now can boot into safe mode and keep on for 1 minute.
need package name to remove it form adb shell.
thanks.

**Comment by cnyyk** [comment]
can't find anything in pm list about tk.zwander.overlaylib.com.android.systemui.
Could you please give me some advice?

**Comment by zacharee** [comment]
That's the package name of what you installed. There's nothing else it could be.

**Comment by cnyyk** [comment]
could you please tell me what https://github.com/zacharee/OneUITunerRedesign/blob/master/oneuituner_SIGNED.apk does after installed?
I'm still try to fix the s9 brick.
If I know what apk does, should be possible to fix.
Thanks

**Comment by cnyyk** [comment]
Finally, fixed it.

> @xerostratos said: Bro, just enter download mode ,flash latest firmware with Odin, but don't use csc use home csc your data will be fine and get rid of you problem.and use package disabler for take the apps you don't want.
via
https://forum.xda-developers.com/showpost.php?p=81980947&postcount=3

**Comment by DieselConsumer** [comment]
All you had to do was enter safe mode, enable debugging and run this: adb uninstall tk.zwander.overlaylib.com.android.systemui
